name: Database update

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Run database update
        run: yarn run update-database
        env:
  DATABASE_HOST: ${{ secrets.DB_HOSTNAME }}
  DATABASE_USERNAME: ${{ secrets.DB_USER }}
  DATABASE_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DATABASE_NAME: ${{ secrets.DB_NAME }}
