name: Update database
on:
  push:
    branches:
      - main
jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: liquibase-github-actions/update-sql@v4.25.0
      with:
        changelogFile: ./wp_site2.sql
        url: ${{ secrets.DB_HOSTNAME }}
        username: ${{ secrets.DB_USERNAME }}
        password: ${{ secrets.DB_PASSWORD }}
