name: Mise à jour de la base de données SQL
on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Mettre à jour la base de données
        uses: microsoft/mssql-database-run-script@v1
        with:
          server: ${{ DB_HOSTNAME }}
          database: ${{ DB_NAME }}
          user: ${{ DB_USER }}
          password: ${{ DB_PASSWORD }}
          script: ./update.sql
          sql-server-version: '15.0'
