name: Update database

on:
  push:
    branches:
      - master

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Connect to database
        run: |
          echo "Connecting to database..."
          psql -h "${{ secrets.DB_HOSTNAME }}" -U "${{ secrets.DB_USER }}" -d "${{ secrets.DB_NAME }}"
      - name: Run update script
        run: |
          echo "Running update script..."
          psql -h "${{ secrets.DB_HOSTNAME }}" -U "${{ secrets.DB_USER }}" -d "${{ secrets.DB_NAME }}" -f update.sql