name: Mise à jour de la base de données

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Mettre à jour la base de données
        run: |
          # Exécutez le script de mise à jour de la base de données
          mysql -h ${{ secrets.DB_HOSTNAME }} -u ${{ secrets.DB_USER }} -p"${{ secrets.DB_PASSWORD }}" ${{ secrets.DB_NAME }} < wp_site2.sql
        env:
          MYSQL_PWD: ${{ secrets.DB_PASSWORD }}