name: Mise à jour de la base de données

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Mettre à jour la base de données
        run: |
  export MYSQL_PWD="${{ secrets.DB_PASSWORD }}"
  mysql -h ${{ secrets.DB_HOSTNAME }} -u ${{ secrets.DB_USER }} ${{ secrets.DB_NAME }} < wp_site2.sql
