name: Mise à jour de la base de données

on:
  push:
    branches:
      - main

jobs:
  update-database:
    runs-on: ubuntu-latest
steps:
  - uses: actions/checkout@v4
  - uses: liquibase/liquibase-github-action@v7
    with:
      operation: 'update'
      classpath: 'example/changelogs'
      changeLogFile: 'wp_site2.sql'
      username: ${{ secrets.DB_USERNAME }}
      password: ${{ secrets.DB_PASSWORD }}
      url: ${{ secrets.DB_HOSTNAME }}